---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: blue-build-dmoseley
# description will be included in the image's metadata
description: Personal OS image for drewmoseley.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pvermeer/chromebook-linux-audio/repo/fedora-%OS_VERSION%/pvermeer-chromebook-linux-audio-fedora-%OS_VERSION%.repo
      - https://terra.fyralabs.com/terra.repo
    install:
      - NetworkManager-fortisslvpn
      - NetworkManager-fortisslvpn-gnome
      - aspell
      - aspell-en
      - autoconf
      - automake
      - bmap-tools
      #- chromebook-linux-audio
      - cmake
      #- cros-keyboard-map
      - emacs
      - keyd
      - libstdc++-static.x86_64
      - libtool
      - mkosi
      - wev
    remove:
      - code

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - ca.desrt.dconf-editor
          - com.bitwarden.desktop
          - com.github.tchx84.Flatseal
          - com.github.zocker_160.SyncThingy
          - com.google.Chrome
          - com.mattjakeman.ExtensionManager
          - com.slack.Slack
          - com.thincast.client
          - io.github.dvlv.boxbuddyrs
          - io.github.flattool.Warehouse
          - io.missioncenter.MissionCenter
          - io.unobserved.espansoGUI
          - net.cozic.joplin_desktop
          - org.fedoraproject.MediaWriter
          - org.gimp.GIMP
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Connections
          - org.gnome.Contacts
          - org.gnome.DejaDup
          - org.gnome.Logs
          - org.gnome.Loupe
          # - org.gnome.Loupe.HEIC
          - org.gnome.Maps
          - org.gnome.NautilusPreviewer
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.World.PikaBackup
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gnome.font-viewer
          - org.inkscape.Inkscape
          - org.mozilla.Thunderbird
          - org.mozilla.firefox
          - org.raspberrypi.rpi-imager
          - org.remmina.Remmina
          - org.videolan.VLC
          - us.zoom.Zoom
      - scope: user # Also add Flathub user repo, but no user packages

  - type: bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update

  - type: gnome-extensions
    install:
      - Advanced Weather Companion
      - 779 # Clipboard Indicator by Tudmotu
      - Easy Docker Containers
      - Night Theme Switcher
      - Tailscale Status
      - Vitals

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: chezmoi
    repository: "git@github.com:drewmoseley/dotfiles-chezmoi.git"
    all-users: true
    file-conflict-policy: replace

  - type: copy
    src: gdm-custom.conf
    dest: /usr/etc/gdm/custom.conf

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
