---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue-build-dmoseley
description: Personal OS image for drewmoseley.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

modules:
  - type: kargs
    kargs:
      - systemd.show_status=1
      - rd.udev.log_priority=debug
      - plymouth.enable=0
      - rd.plymouth=0
      - plymouth.ignore-serial-consoles
      - systemd.show_status=1
      - rd.udev.log_priority=debug

  - type: files
    files:
      - source: system
        destination: /

  - type: files
    files:
      - source: ups/msmtp-mail.sh
        destination: /etc/ups/msmtp-mail.sh
        owner: root
        group: nut
        mode: 0750
      - source: ups/nut.conf
        destination: /etc/ups/nut.conf
        owner: root
        group: nut
        mode: 0640
      - source: ups/upsmon.conf
        destination: /etc/ups/upsmon.conf
        owner: root
        group: nut
        mode: 0640
      - source: ups/upssched-cmd
        destination: /etc/ups/upssched-cmd
        owner: root
        group: nut
        mode: 0750
      - source: ups/upssched.conf
        destination: /etc/ups/upssched.conf
        owner: root
        group: nut
        mode: 0640
      - source: ups/.msmtprc
        destination: /etc/ups/.msmtprc
        owner: root
        group: nut
        mode: 0640
      - source: ups/nut-events
        destination: /etc/logrotate.d/nut-events
        owner: root
        group: root
        mode: 0644

  - type: bling
    install:
      - dconf-update-service
      #- ublue-update # https://github.com/ublue-os/ublue-update

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pvermeer/chromebook-linux-audio/repo/fedora-%OS_VERSION%/pvermeer-chromebook-linux-audio-fedora-%OS_VERSION%.repo
      - https://terra.fyralabs.com/terra.repo
      - https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    install:
      - NetworkManager-fortisslvpn
      - NetworkManager-fortisslvpn-gnome
      - ansible
      - apt
      - aspell
      - aspell-en
      - autoconf
      - automake
      - bmap-tools
      - btrfs-progs
      #- chromebook-linux-audio
      - cmake
      #- cros-keyboard-map
      - debootstrap
      - dosfstools
      - e2fsprogs
      - emacs
      - g++
      - git-credential-manager
      - grub2
      - java-21-openjdk-headless
      - keyd
      - libstdc++-static.x86_64
      - libtool
      - libvirt-devel
      #- mkosi
      - nut-client
      - parted
      - pass
      - pcsc-tools
      - qemu-user-static
      - systemd-ukify
      - grub2-tools
      - syncthing
      - vagrant
      - wev
    remove:
      - code
    optfix:
      - /vagrant
      - /uptane-sign

  # Delete Fedora packaged docker and friends
  - type: rpm-ostree
    remove:
      - docker-ce-cli
      - docker-ce
      - docker-ce-rootless-extras
      - docker-compose-plugin
      - docker-buildx-plugin

  # Install Docker.com packaged docker and friends
  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - ca.desrt.dconf-editor
          - com.bambulab.BambuStudio
          - com.bitwarden.desktop
          - com.github.tchx84.Flatseal
          - com.google.Chrome
          - com.mattjakeman.ExtensionManager
          - com.prusa3d.PrusaSlicer
          - com.slack.Slack
          - com.thincast.client
          - com.todoist.Todoist
          - com.ultimaker.cura
          - io.github.dvlv.boxbuddyrs
          - io.github.flattool.Warehouse
          - io.github.martchus.syncthingtray
          # - io.github.softfever.OrcaSlicer
          - io.missioncenter.MissionCenter
          - io.podman_desktop.PodmanDesktop
          - io.unobserved.espansoGUI
          - net.cozic.joplin_desktop
          - org.fedoraproject.MediaWriter
          - org.gimp.GIMP
          - org.gnome.Boxes
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Connections
          - org.gnome.Contacts
          - org.gnome.DejaDup
          - org.gnome.Logs
          - org.gnome.Loupe
          # - org.gnome.Loupe.HEIC
          - org.gnome.Maps
          - org.gnome.NautilusPreviewer
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.World.PikaBackup
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gnome.font-viewer
          - org.inkscape.Inkscape
          - org.mozilla.Thunderbird
          - org.mozilla.firefox
          - org.raspberrypi.rpi-imager
          - org.remmina.Remmina
          - org.videolan.VLC
          - us.zoom.Zoom
      - scope: user

  - type: gnome-extensions
    install:
      - 779 # Clipboard Indicator
      - Easy Docker Containers
      - Night Theme Switcher
      - Tailscale Status
      - Vitals
      - Weather O'Clock

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: chezmoi
    repository: "git@github.com:drewmoseley/dotfiles-chezmoi.git"
    all-users: true
    file-conflict-policy: replace

  - type: gschema-overrides
    include:
      - dmoseley.gschema.override

  - type: script
    scripts:
      - install-uptane-sign.sh

  - type: signing

  - type: systemd
    system:
      enabled:
        - kargs-cleanup.service
        - ext.automount
        - work.automount
        - setup-user-groups.service
        - storage-health.timer
        - resource-logger.timer
      masked:
        - plymouth-start.service
        - plymouth-quit.service
        - plymouth-quit-wait.service
        - plymouth-read-write.service
