---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue-build-dmoseley-chromebook
description: Personal OS image for drewmoseley on HP chromebook.
base-image: ghcr.io/drewmoseley/blue-build-dmoseley
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - pvermeer/chromebook-linux-audio
    install:
      packages:
        - chromebook-linux-audio

  # Terra is installed in bluefin at the moment but disabled by default.
  - type: dnf
    install:
      packages:
        - python3-libfdt
        - repo: terra
          packages:
            - cros-keyboard-map
