---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue-build-dmoseley-chromebook
description: Personal OS image for drewmoseley on HP chromebook.
base-image: ghcr.io/drewmoseley/build-build-dmoseley
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - pvermeer/chromebook-linux-audio
    install:
      packages:
        - chromebook-linux-audio
        - cros-keyboard-map
