---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue-build-dmoseley
description: Personal OS image for drewmoseley.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: files
    files:
      - source: ups/nut.conf
        destination: /etc/ups/nut.conf
        owner: root
        group: nut
        mode: 0640
      - source: ups/upsmon.conf
        destination: /etc/ups/upsmon.conf
        owner: root
        group: nut
        mode: 0640
      - source: ups/upssched-cmd
        destination: /etc/ups/upssched-cmd
        owner: root
        group: nut
        mode: 0750
      - source: ups/upssched.conf
        destination: /etc/ups/upssched.conf
        owner: root
        group: nut
        mode: 0640
      - source: ups/nut-events
        destination: /etc/logrotate.d/nut-events
        owner: root
        group: root
        mode: 0644

  - type: bling
    install:
      - dconf-update-service

  - type: script
    scripts:
      - install-uptane-sign.sh

  - type: dnf
    install:
      packages:
        - NetworkManager-fortisslvpn
        - NetworkManager-fortisslvpn-gnome
        - ansible
        - apt
        - aspell
        - aspell-en
        - autoconf
        - automake
        - bmap-tools
        - cmake
        - debootstrap
        - emacs
        - g++
        - java-21-openjdk-headless
        - libstdc++-static.x86_64
        - libtool
        - libvirt-devel
        - nut-client
        - pass
        - pcsc-tools
        - systemd-ukify
        - syncthing
        - wev
    optfix:
      - /uptane-sign
    remove:
      packages:
        - code

  # Delete Fedora packaged docker and friends
  - type: dnf
    remove:
      packages:
        - moby-engine
        - moby-engine-daemon
        - docker-compose-plugin
        - docker-buildx-plugin
        - podman-docker
        - docker-ce
        - docker-ce-cli
        - docker-ce-rootless-extras
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

  # Install Docker.com packaged docker and friends
  - type: dnf
    repos:
      files:
        - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

  - type: dnf
    repos:
      copr:
        - derenderkeks/proxmox-backup-client
        - pvermeer/chromebook-linux-audio
    install:
      packages:
        - proxmox-backup-client
        #- chromebook-linux-audio
        #- cros-keyboard-map
      skip-unavailable: true

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - ca.desrt.dconf-editor
          - com.bambulab.BambuStudio
          - com.bitwarden.desktop
          - com.github.tchx84.Flatseal
          - com.google.Chrome
          - com.mattjakeman.ExtensionManager
          - com.prusa3d.PrusaSlicer
          - com.slack.Slack
          - com.thincast.client
          - com.todoist.Todoist
          - com.ultimaker.cura
          - io.github.dvlv.boxbuddyrs
          - io.github.flattool.Warehouse
          - io.github.martchus.syncthingtray
          # - io.github.softfever.OrcaSlicer
          - io.missioncenter.MissionCenter
          - io.podman_desktop.PodmanDesktop
          - io.unobserved.espansoGUI
          - net.cozic.joplin_desktop
          - org.fedoraproject.MediaWriter
          - org.gimp.GIMP
          - org.gnome.Boxes
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Connections
          - org.gnome.Contacts
          - org.gnome.DejaDup
          - org.gnome.Logs
          - org.gnome.Loupe
          # - org.gnome.Loupe.HEIC
          - org.gnome.Maps
          - org.gnome.NautilusPreviewer
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.World.PikaBackup
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gnome.font-viewer
          - org.inkscape.Inkscape
          - org.mozilla.Thunderbird
          - org.mozilla.firefox
          - org.raspberrypi.rpi-imager
          - org.remmina.Remmina
          - org.videolan.VLC
          - us.zoom.Zoom
      - scope: user

  - type: gnome-extensions
    install:
      - 779 # Clipboard Indicator
      - Easy Docker Containers
      - Night Theme Switcher
      - Tailscale Status
      - Vitals
      - Weather O'Clock

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: chezmoi
    repository: "git@github.com:drewmoseley/dotfiles-chezmoi.git"
    all-users: true
    file-conflict-policy: replace

  - type: gschema-overrides
    include:
      - dmoseley.gschema.override

  - type: signing

  - type: systemd
    system:
      enabled:
        - docker.service
        - docker.socket
        - ext.automount
        - work.automount
        - setup-user-groups.service
        - storage-health.timer
        - resource-logger.timer
        - swapfile-setup.service
        - var-swapfile.swap
        - proxmox-backup.timer
