#!/bin/sh

set -eu

MAIL_TO="drew.moseley@gmail.com"

log() {
  SUBJECT="$1"
  BODY="$2"
  logger -t upssched-cmd "$SUBJECT - $BODY"
  echo "$SUBJECT - $BODY" >> /var/log/nut-events.log
  [ "$3" != "--no-mail"] && echo "$BODY" | mail -s "$SUBJECT" "$MAIL_TO"
}

case "$1" in
  fsd)
    log "NUT $(hostname -s): Forced shutdown received" \
      "This client received FSD from the NUT server and will shut down now.
Time: $(date)
Host: $(hostname)"
    /usr/sbin/upsmon -c fsd
    ;;
  shutdown)
    log "NUT $(hostname -s): Shutdown proceeding" \
      "This client is executing its shutdown sequence.
Time: $(date)
Host: $(hostname)"
    ;;
  commbad)
    log "NUT $(hostname -s): Communication lost" "upsmon reported COMMBAD at $(date)" --no-mail
    ;;
  commok)
    log "NUT $(hostname -s): Communication restored" "upsmon reported COMMOK at $(date)" --no-mail
    ;;
  onbatt)
    log "NUT $(hostname -s): On battery" "Client detected UPS on battery at $(date)"
    ;;
  online)
    log "NUT $(hostname -s): Back on line power" "Client detected UPS back on line at $(date)"
    ;;
  lowbatt)
    log "NUT $(hostname -s): Battery low" "Client reports UPS battery low at $(date)"
    ;;
  *)
    log "NUT $(hostname -s): $1" "Unrecognized command: $1 at $(date)" --no-mail
    ;;
esac
