#!/bin/sh

MAIL_TO="drew.moseley@gmail.com"

send_mail() {
  SUBJECT="$1"
  BODY="$2"
  logger -t upssched-cmd "$SUBJECT - $BODY"
  echo "$BODY" | /etc/ups/msmtp-mail.sh -s "$SUBJECT" "$MAIL_TO"
}

case "$1" in
  fsd)
    send_mail "NUT $(hostname -s): Forced shutdown received" \
      "This client received FSD from the NUT server and will shut down now.
Time: $(date)
Host: $(hostname)"
    /usr/sbin/upsmon -c fsd
    ;;
  shutdown)
    send_mail "NUT $(hostname -s): Shutdown proceeding" \
      "This client is executing its shutdown sequence.
Time: $(date)
Host: $(hostname)"
    ;;
  commbad)
    send_mail "NUT $(hostname -s): Communication lost" "upsmon reported COMMBAD at $(date)"
    ;;
  commok)
    send_mail "NUT $(hostname -s): Communication restored" "upsmon reported COMMOK at $(date)"
    ;;
  onbatt)
    send_mail "NUT $(hostname -s): On battery" "Client detected UPS on battery at $(date)"
    ;;
  online)
    send_mail "NUT $(hostname -s): Back on line power" "Client detected UPS back on line at $(date)"
    ;;
  *)
    # No mail for other events (quiet client)
    logger -t upssched-cmd "Ignored event: $1"
    ;;
esac
